# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lassiwebapptest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://lassiwebapprn.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d170a80b27b6495f8ad8779b3af1f775 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_274f0371a6dc4affaeac60102b5598fc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lassiwebapprn.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d170a80b27b6495f8ad8779b3af1f775 }}/lassiwebapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lassiwebapptest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9c828bbc551346d598600c66cd6b7db3 }}
        images: 'lassiwebapprn.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d170a80b27b6495f8ad8779b3af1f775 }}/lassiwebapp:${{ github.sha }}'